# Generated by Django 3.1 on 2020-08-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='phone',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('In Door', 'In Door'), ('Out Door', 'Out Door')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
